import type { Metadata } from 'next';
import { Inter, Exo_2 } from 'next/font/google';
import '../app/globals.css';
import { BackgroundManager } from '@/components/Backgrounds/BackgroundManager';
import ChosenBackground from '@/components/Backgrounds/ChosenBackground';
import { BackgroundProvider } from '@/components/Backgrounds/BackgroundContext';
import BackgroundWrapper from '@/components/Backgrounds/BackgroundWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const exo2 = Exo_2({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export default function RootLayout({ children, }: { children: React.ReactNode; }) {

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${exo2.className} bg-cover bg-center 
        bg-no-repeat bg-fixed text-white`}
      >      <BackgroundProvider>
          <BackgroundWrapper>
            <div className="flex flex-col min-h-screen">
              <div className="w-full max-w-md mx-auto px-4 pt-3 pb-16">
                {children}
              </div>
            </div>
          </BackgroundWrapper>
        </BackgroundProvider>
      </body>
    </html>
  );
}
